// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjmO_MimhEpGZibo4Wfx5txCLay_PNB18',
    appId: '1:458809642203:web:b954c91b143e381f3e10fe',
    messagingSenderId: '458809642203',
    projectId: 'hackgt-5b60a',
    authDomain: 'hackgt-5b60a.firebaseapp.com',
    databaseURL: 'https://hackgt-5b60a-default-rtdb.firebaseio.com',
    storageBucket: 'hackgt-5b60a.appspot.com',
    measurementId: 'G-PH94VH9LQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsqr_GLyuK90u-kh2AzCj0ooWCiIQleLY',
    appId: '1:458809642203:android:29f4d57c3cd805053e10fe',
    messagingSenderId: '458809642203',
    projectId: 'hackgt-5b60a',
    databaseURL: 'https://hackgt-5b60a-default-rtdb.firebaseio.com',
    storageBucket: 'hackgt-5b60a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF-GAp0ai6sIFuliI9MvB1lOuWB1uZPsU',
    appId: '1:458809642203:ios:bead9e3b3eba4b493e10fe',
    messagingSenderId: '458809642203',
    projectId: 'hackgt-5b60a',
    databaseURL: 'https://hackgt-5b60a-default-rtdb.firebaseio.com',
    storageBucket: 'hackgt-5b60a.appspot.com',
    iosBundleId: 'com.example.hackgt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF-GAp0ai6sIFuliI9MvB1lOuWB1uZPsU',
    appId: '1:458809642203:ios:71417a56c7d8669a3e10fe',
    messagingSenderId: '458809642203',
    projectId: 'hackgt-5b60a',
    databaseURL: 'https://hackgt-5b60a-default-rtdb.firebaseio.com',
    storageBucket: 'hackgt-5b60a.appspot.com',
    iosBundleId: 'com.example.hackgt.RunnerTests',
  );
}
